### PR TITLE
Enable a patch by Lucas only when using non-Cygwin LaTeX from Cygwin

### PR DESCRIPTION
**Pull request by lemniscati**
This is another candidate to fix failure on cygwin #20, keeping Lucas' patch #3 (72d12db07a49f9098e470fc770fe3f6e5036b9d5) effective only when using non-Cygwin LaTeX from a Cygwin environment.

### CODE REVIEW

**Comment by lemniscati** [comment]
Added two commits to #22.

* It works fine on a pure Cygwin environment (or updated on 2020/05/14).
* It works fine on an environment of Ununtu 18.04 LTS.
* It may work with `pdflatex` of MiKTeX on Windows through a Cygwin environment.
  I've tested in a following situation and it works:
  * MiKTeX has been installed by `basic-miktex-2.9.7417-x64.exe`.
  * Cygwin has been installed (or updated on 2020/05/14) and `/usr/bin/pdflatex` been deleted (or just renamed).
  * MiKTeX has asked to install some packages: `pdfpages`, `eso-pic`, `atbegshi`, `infwarerr`, `ltxmcds`, `pdflscape`.

**Comment by lemniscati** [comment]
About an environment MiKTeX on Windows through Cygwin.
I've tested in a following situation and it works:
* MiKTeX has been installed by basic-miktex-2.9.7417-x64.exe.
* Cygwin has been installed by https://cygwin.com/setup-x86_64.exe (2020/05/14) 
* MiKTeX has asked to install some packages as my previous comment.

Additionally, I've noticed that when we use a `--keepinfo` option, MiKTeX asks more packages, and the option does not work as expected. But it is another issue #23.

**Comment by lemniscati** [comment]
@DavidFirth, thank you for developing `pdfjam`.
Would you mind merging this PR?

**Comment by DavidFirth** [comment]
Many thanks @lemniscati for all this, it is much appreciated.

My time for pdfjam is nonexistent at present, so reviewing this will have to wait until I next find time to work on pdfjam -- sorry.  In the meantime, since I do not have cygwin or Windows here, it would be good to hear from anyone else who might be able to test this patch.

**Comment by lemniscati** [comment]
All right.

**Pull request merged**
